[package]
name = "bobbbay"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5.7"
color-eyre = "0.6.1"
lazy_static = "1.4.0"
serde = "1.0.137"
tera = "1.16.0"
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["full"] }
tower = "0.4.12"
tower-http = { version = "0.3.4", features = ["fs", "trace"] }
tracing = "0.1.35"
tracing-error = "0.2.0"
tracing-subscriber = "0.3.11"

[package.metadata.nix]
build = true
