[package]
name = "bobbbay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.1"
tracing = "0.1.35"
tracing-error = "0.2.0"
tracing-subscriber = "0.3.11"
