[package]
name = "bobbbay"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.2"
color-eyre = "0.6.2"
fs_extra = "1.2.0"
glob = "0.3.1"
grass = "0.12.3"
lazy_static = "1.4.0"
pandoc = "0.8.10"
serde = "1.0.151"
tera = "1.17.1"
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.5", features = ["fs", "trace"] }
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-subscriber = "0.3.16"

[package.metadata.nix]
build = true
